---
- name: Auto Heal Demo
  hosts: servers
  tasks:
    - name: Solve the problem detected by Dynatrace
      command: rm -rf /tmp/inodes/*
      
    - name: Confirm to OPs team
      command: touch /tmp/inodes/auto-healed-by-ansible.txt
      
      
   
