---
- name: Auto Heal Demo
  hosts: servers
  tasks:
    - name: Start the agent 
      shell: rm -rf /tmp/inodes/*
      
    - name: Create a file 
      command: touch /tmp/inodes/auto-healed-by-ansible.txt
      
      
   
