---
- name: Auto Heal Demo
  hosts: webservers
  gather_facts: no
  tasks:
   - name: Sleep for 3 minutes
     wait_for:
       timeout: 60
     delegate_to: localhost

   - name: Create a directory to keep logs
     file:
       path: /opt/logs_archive
       state: "{{ item }}"
     with_items:
       - absent
       - directory

   - name: Move data from logs directory to archive directory
     shell: cp /var/lib/data{{ item }} /opt/logs_archive/{{ item }}
     delegate_to: "{{ inventory_hostname }}"
     with_items:
       - test.file
     ignore_errors: yes

   - name: Clean the old log files
     file:
       path: /app/logs/{{ item }}
       state: absent
     with_items:
        - test.file
     ignore_errors: yes
