---
- name: Auto Heal Demo
  hosts: localhost
  tasks:
    - name: fix the problem
      file:
        path: /tmp/inodes
        state: "{{ item }}"
      with_items:
        - absent
        - directory

    - name: Create a file
      command: touch /tmp/inodes/auto-healed-by-ansible.txt
